#:schema node_modules/wrangler/config-schema.json
# wrangler.toml is used for dev mode
# for production, use the cloudflare dashboard
# empty values are placeholders, replace them with your own values


name = "brand-template-xn"
compatibility_date = "2023-10-30"
pages_build_output_dir = "./build/client"
